### ISSUE TITLE
[secio] create report with only message sending

### ISSUE THREAD

**Issue by dignifiedquire** [moshisushi/ipfs-lab#1]
Generating keys is known to be not the fastest operation and hard to optimise currently. Sending messages might be more interesting too look at, and much more likely to cause issues when being slow as it is done the whole time. So it would be great if you could adjust the benches to only measure the sending and receiving part.

**Comment by moshisushi** [comment]
@dignifiedquire Ah yeah David Dias told me that when I showed him this stuff some time ago, so that's why the report has "Send time" vs "Total time", where send time excludes the key generation.

**Comment by dignifiedquire** [comment]
Ahh cool, I missed that line :) disregard this then
